config/routes.rb
Rails.application.routes.draw do
  root to: 'games#home'
  get 'new', to: 'games#new', as: :new
  get 'score', to: 'games#score', as: :score
  delete 'clear', to: 'games#clear', as: :clear
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'
require 'date'

class GamesController < ApplicationController

  def new
    session[:highscore] ||= []

    letter_array = []
    10.times do
      letter_array << ("A".."Z").to_a.sample
    end
    @letters = letter_array
    @start = Time.now.to_f
  end

  def score
    @answer = params[:answer]
    @letters = params[:letters]
    @time = Time.now.to_f - params[:start].to_f
    @score = (params[:answer].length - (@time / 120)).round(2)
    @url = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FNTY1kHmcLsCsg%2Fgiphy.gif&f=1&nofb=1"

    grid_hash = {}
    ("A".."Z").to_a.each { |letter| grid_hash[letter] = 1 }

    @answer_array = @answer.upcase.split('').sort
    @letters_array = @letters.upcase.split(' ').sort

    @letters_array.each { |letter| grid_hash[letter] += 1 }
    @answer_array.each { |letter| grid_hash[letter] = grid_hash[letter] - 1 }
    allowed = grid_hash.values.all?(&:positive?)

    checker = JSON.parse(open("https://wagon-dictionary.herokuapp.com/#{@answer}").read)
    word = checker['found']

    if @answer == ''
      @outcome = 'Cheater! Empty answer! - You loose'
      @score = "LOST"
    elsif word == false && allowed == false
      @outcome = 'Not an allowed word and not even English! - You loose'
      @score = "LOST"
    elsif word == true && allowed == false
      @outcome = 'English word, but not allowed - You loose'
      @score = "LOST"
    elsif word == false && allowed == true
      @outcome = "You are allowed to use this word, but it's not english - You loose"
      @score = "LOST"
    else
      @outcome = "You won with #{@score} points after #{@time.round(2)} seconds"
      @url = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi1.wp.com%2Fbestanimations.com%2FHolidays%2FFireworks%2Ffireworks%2Fba-awesome-colorful-fireworks-animated-gif-image-s.gif&f=1&nofb=1"
    end

    if @score == "LOST"
    else
      session[:highscore] << { "answer" => @answer, "score" => @score }
    end
    @highscore = session[:highscore].sort_by { |hsh| hsh["score"] }.reverse
  end

  def clear
    reset_session
    redirect_to :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_controller_helper.rb
module GamesControllerHelper
end

app/views/games/home.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>


  <%= link_to "START NEW GAME", "/new", class: "btn btn-primary"%>

app/views/games/new.html.erb
<br>
<br>
<br>
<br>
<br>
<h1>Which word can you create?</h1>

<% @letters.each do |letter| %>
<ul>
  <li><%= letter %> </li>
</ul>
<% end %>
<br>

<form action="/score" method="get">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :letters, @letters %>
  <%= hidden_field_tag :start, @start %>
  <input type="text" name="answer" placeholder="What's the word?">
  <input type="submit" value="Let's go">
</form>

app/views/games/score.html.erb
<br>
<h1><strong>Outcome</strong></h1>

<img id="drag1" src=<%= @url %> width="600" height="250">


<p>Your answer was <strong><%= params[:answer] %></strong>.</p>

<br>
<h2><%= @outcome %></h2>
<br>

<br>
<%= link_to "START NEW GAME", new_path , class: "btn btn-primary"%>
<br>
<br>
<h2>Highscore</h2>

<table class="table">
  <tr>
    <th>Word</th>
    <th>Score</th>
  </tr>

  <% @highscore.each do |result| %>
    <tr><td><%= result["answer"] %></td><td><%= result["score"] %></td></tr>
  <% end %>

</table>
<br>
  <%= link_to "Clear Highscore", clear_path , class: "btn btn-primary", method: :delete%>

<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manuscho Game Suite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  </head>

  <body>
    <div class="background">
      <h1 class="title">Manuscho Game Studios</h1>
      <div class="container">
        <%= yield %>
      </div>
      <footer class="page-footer font-small fixed-bottom text-secondary">
        <div class="footer-copyright text-center py-2">© 2020 Copyright: Manuscho</div>
      </footer>
    </div>
  </body>
</html>